# Generated by Django 3.0.6 on 2020-06-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0003_auto_20200605_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='linked_to',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
