# Generated by Django 3.0.6 on 2020-06-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0004_comment_linked_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
